<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.907" timestamp="2025-01-08T06:24:25.247093+11:00" hostname="Vics-MacBook-Air.local"><testcase classname="" name="unit.test_dashboard" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/Shared/cursor/project_management_dashboard/tests/unit/test_dashboard.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
.venv/lib/python3.9/site-packages/_pytest/python.py:493: in importtestmodule
    mod = import_path(
.venv/lib/python3.9/site-packages/_pytest/pathlib.py:587: in import_path
    importlib.import_module(module_name)
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1030: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1007: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:986: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:680: in _load_unlocked
    ???
.venv/lib/python3.9/site-packages/_pytest/assertion/rewrite.py:184: in exec_module
    exec(co, module.__dict__)
tests/unit/test_dashboard.py:7: in &lt;module&gt;
    from dashboard.main import display_metrics, update_metrics
E   ImportError: cannot import name 'display_metrics' from 'dashboard.main' (/Users/Shared/cursor/project_management_dashboard/dashboard/main.py)</error></testcase></testsuite></testsuites>
